# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - homedecorwin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://crcrossborderdev.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7e55a8430052430cb497f042e8a19826 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_734546aed61348559ebb7612407ee092 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: crcrossborderdev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7e55a8430052430cb497f042e8a19826 }}/mcr.microsoft.com/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'homedecorwin'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_37a9f32f722f479889a6e3fc9ef32fbd }}
        images: 'crcrossborderdev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7e55a8430052430cb497f042e8a19826 }}/mcr.microsoft.com/appsvc/wordpress-alpine-php:${{ github.sha }}'